### ISSUE TITLE
Unable to fetch database

### ISSUE THREAD

**Issue by dfucci** [interlynk-io/sbomdb#3]
When trying to pull the file contents from LFS (`git lfs pull`), I got the following:  
`batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/interlynk-io/sbomdb.git/info/lfs'`

Is there a chance you can share the SBOM database in other ways?

**Comment by surendrapathak** [comment]
HI @dfucci - Certainly. Apologies that you ran into it. If you can share your email to : hello@interlynk.io, we can share the Dd.

**Comment by surendrapathak** [comment]
It's now available at : https://s3.amazonaws.com/app.interlynk.io/static/db/sbomlc.db
